name: CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    name: Mathlib Test Suite
    # This job runs the test suite for mathlib using pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      - name: Run tests
        run: pytest
